#!/bin/bash

# export PATH=/usr/bin/gcc-arm-none-eabi-10-2020-q4-major/bin:$PATH

CHIPID="best1306p"
# TARGET_LIST="ATL-115"
TARGET_LIST="best1306p"
PRODUCT_TYPE=earbuds
COMMAND=$1
ANC_USB_ENABLED=0
BES_LIB_DIR="lib/bes/best1306p/PRO_0008"

echo $COMMAND
echo $TARGET_LIST


set -e
################################### var define ###################################
APP_CUSTOMER_CFG="IGNORE_POWER_ON_KEY_DURING_BOOT_UP=1 IS_AUTOPOWEROFF_ENABLED=0 APP_TRACE_RX_ENABLE=1 APP_RX_API_ENABLE=1 AUDIO_DEBUG_CMD=0 \
                 TRACE_BUF_SIZE=40*1024 USE_TRACE_ID=0 BES_LIB_DIR=$BES_LIB_DIR"

CAPSENSOR_CFG="CAPSENSOR_ENABLE=1 CAPSENSOR_AT_MCU=1  CAPSENSOR_TOUCH=1 CAPSENSOR_WEAR=1 CAPSENSOR_SLIDE=0 CAPSENSOR_TRACE_DEBUG=0 \
        CHIP_CAPSENSOR_VER=4 CAPSENSOR_FP_MODE=1 CAPSENSOR_SPP_SERVER=0 CAPSENSOR_WEAR_USE_ONE_PAD=1"

BLE_CFG="BLE=1 GATT_OVER_BR_EDR=1 GFPS_ENABLE=1 SWIFT_ENABLE=1"

OTA_CFG="BES_OTA=1 OTA_BIN_COMPRESSED=1"

TWS_CFG="POWER_ON_ENTER_TWS_PAIRING_ENABLED=1 FREE_TWS_PAIRING_ENABLED=0"

FREEMAN_CFG="POWER_ON_ENTER_FREEMAN_PAIRING_ENABLED=1 FREEMAN_ENABLED_STERO=1"

SPEECH_CFG="SPEECH_TX_DC_FILTER=1 SPEECH_TX_AEC2FLOAT=1 SPEECH_TX_1MIC_NS=1 SPEECH_TX_EQ=1"

SPEECH_2MIC_CFG="SPEECH_TX_DC_FILTER=1 SPEECH_TX_2MIC_NS8=1 SPEECH_TX_EQ=0"

DECODE_DECODER_CFG="A2DP_AAC_ON=1 A2DP_LDAC_ON=0 A2DP_LHDC_ON=0 A2DP_LHDC_V3=0 A2DP_LHDCV5_ON=0 AAC_IN_ROM=1 CVSD_IN_ROM=1"

CP_CFG="A2DP_CP_ACCEL=1 SCO_CP_ACCEL=1 CHIP_HAS_CP=1 RAMCP_SIZE=0x4000 RAMCPX_SIZE=0x10000 FAST_XRAM_SECTION_SIZE=0x6000 UNIFY_HEAP_ENABLED=0"

NO_CP_CFG="A2DP_CP_ACCEL=0 SCO_CP_ACCEL=0 CHIP_HAS_CP=0 RAMCP_SIZE=0 RAMCPX_SIZE=0 FAST_XRAM_SECTION_SIZE=0x12000"

SYS_CFG=" ALLOW_WARNING=1"

ANC_CFG="ANC_ENABLE=1 ANC_ASSIST_ENABLED=1 VOICE_ASSIST_NOISE=0 VOICE_ASSIST_CUSTOM_LEAK_DETECT=0 VOICE_ASSIST_CUSTOM_LEAK_DETECT=0 ANC_PROD_TEST=1 TOTA_v2=1"

AUDIO_CFG="AUDIO_BASS_ENHANCER=0 AUDIO_DRC=0 AUDIO_LIMITER=0 AUDIO_ADAPTIVE_VOLUME=0"


################################### end of var define ###################################
if [[ "$COMMAND" == "clean" ]];
then
    make T=$TARGET_LIST clean -j64||{ echo "$LINENO command failed"; exit 1; }
elif [[ "$COMMAND" == 'PROG' ]];
then
	make T=programmer_inflash CHIP=$CHIPID DEBUG=1 -j64 ||{ echo "$LINENO command failed"; exit 1; }
elif [[ "$COMMAND" == 'OTA' ]];
then
	make T=prod_test/ota_copy CHIP=$CHIPID OTA_BIN_COMPRESSED=1 DEBUG=1 -j64 ||{ echo "$LINENO command failed"; exit 1; }
elif [[ "$COMMAND" == "gen_lib" ]];
then
    make T=$TARGET_LIST $APP_CUSTOMER_CFG $BLE_CFG $OTA_CFG $TWS_CFG $SPEECH_2MIC_CFG $DECODE_DECODER_CFG $SYS_CFG $CAPSENSOR_CFG $AUDIO_CFG GEN_LIB=1 -j64 ||{ echo "$LINENO command failed"; exit 1; }
    make T=prod_test/ota_copy CHIP=$CHIPID OTA_BIN_COMPRESSED=1 DEBUG=1 BES_LIB_DIR=$BES_LIB_DIR -j64 GEN_LIB=1 ||{ echo "$LINENO command failed"; exit 1; }
elif [[ "$COMMAND" == 'lst' ]];
then
    make T=$TARGET_LIST $APP_CUSTOMER_CFG $BLE_CFG $OTA_CFG $TWS_CFG $SPEECH_2MIC_CFG $DECODE_DECODER_CFG $SYS_CFG $CAPSENSOR_CFG $AUDIO_CFG -j64 lst all ||{ echo "$LINENO command failed"; exit 1; }
else
    make T=$TARGET_LIST $APP_CUSTOMER_CFG $BLE_CFG $OTA_CFG $TWS_CFG $SPEECH_2MIC_CFG $DECODE_DECODER_CFG $SYS_CFG $CAPSENSOR_CFG $AUDIO_CFG -j64 ||{ echo "$LINENO command failed"; exit 1; }
fi
