
TARGET_LIST="best1306p"
CHIPID="best1306p"
COMMAND=$1
set -e

BLE_CFG="BLE=1"

BASE_CFG="OTA_BIN_COMPRESSED=1 BES_LIB_DIR="lib/bes/best1306p/PRO_0005""

AUD_CFG="A2DP_LDAC_ON=1"

ANC_CFG="ANC_ENABLE=1 ANC_ASSIST_ENABLED=1 ANC_PROD_TEST=1 VOICE_ASSIST_NOISE=1"

OTA_CFG="TOTA_v2=1"

ANC_IIR_LMS_CFG="AUDIO_ANC_TT_HW=1 ANC_ASSIST_ENABLED=1 VOICE_ASSIST_FF_IIR_LMS=1 USE_CMSIS_FFT_LEN_1024=1 BECO=1 FIR_LMS_AEC_ENABLED=1 RAMCPX_SIZE=0x3800"

CAPSENSOR_CFG="CAPSENSOR_ENABLE=1 CAPSENSOR_WEAR=1 CAPSENSOR_FAC_CALCULATE=1 CAPSENSOR_TRACE_DEBUG=0 \
        CHIP_CAPSENSOR_VER=4 CAPSENSOR_FP_MODE=1 CAPSENSOR_MEDIAN_FILTERING=1 \
        CAPSENSOR_WEAR_USE_ONE_PAD=1 CAPSENSOR_SPP_SERVER=0"

DUAL_MIC_RECOR_CFG="DUAL_MIC_RECORDING=1 RECORDING_USE_OPUS=1 SINGLE_DEVICE_REC=1 RAMCP_SIZE=0x28000 "

BUILD_CUSTOMER_CFG="$BLE_CFG $BASE_CFG $AUD_CFG $ANC_CFG $ANC_IIR_LMS_CFG $OTA_CFG $CAPSENSOR_CFG $DUAL_MIC_RECOR_CFG \
                    IGNORE_POWER_ON_KEY_DURING_BOOT_UP=1 IS_AUTOPOWEROFF_ENABLED=0 POWER_ON_ENTER_TWS_PAIRING_ENABLED=1 \
                    APP_TRACE_RX_ENABLE=1 APP_RX_API_ENABLE=1 AUDIO_DEBUG_CMD=0 TRACE_BUF_SIZE=40*1024 \
                    BES_OTA=1 FAST_TIMER_COMPENSATE=1"

if [[ "$COMMAND" == "clean" ]];
then
    make T=$TARGET_LIST clean ||{ echo "$LINENO command failed"; exit 1; }
elif [[ "$COMMAND" == "gen_lib" ]];
then
    make T=$TARGET_LIST $BUILD_CUSTOMER_CFG -j64 GEN_LIB=1 ||{ echo "$LINENO USE_LIBcommand failed"; exit 1; }
    make T=prod_test/ota_copy CHIP=$CHIPID DEBUG=1 $BASE_CFG -j64 GEN_LIB=1 ||{ echo "$LINENO command failed"; exit 1; }
elif [[ $1 == 'lst' ]];
then
    make T=$TARGET_LIST $BUILD_CUSTOMER_CFG -j64 lst all ||{ echo "$LINENO command failed"; exit 1; }
else
    make T=prod_test/ota_copy CHIP=$CHIPID DEBUG=1 $BASE_CFG -j64 ||{ echo "$LINENO command failed"; exit 1; }
    echo "make T=$TARGET_LIST $BUILD_CUSTOMER_CFG -j64"
    make T=$TARGET_LIST $BUILD_CUSTOMER_CFG -j64 ||{ echo "$LINENO command failed"; exit 1; }
fi

echo $BUILD_CUSTOMER_CFG