#!/bin/bash

COMMAND=$1
set -e

################################### var define ###################################
LIB_DIR_CFG="BES_LIB_DIR=lib/bes/best1502p/PRO_0004 "
FIR_ANC_CFG="ANC_ENABLE=1 APP_MCPP_CLI=BTH APP_MCPP_BTH_SENS=1 APP_MCPP_CLI=BTH APP_MCPP_BTH_SENS=1 POWER_ON_ENTER_FREEMAN_PAIRING_ENABLED=1 AUDIO_DEBUG_CMD=1 SENSOR_HUB=1 APP_RPC_ENABLE=1 SENS_TRC_TO_MCU=1 \
VOICE_ASSIST_FF_FIR_LMS=1 VOICE_ASSIST_FF_FIR_LMS_BTH_SENS=1 LARGE_SENS_RAM=1 SENS_FIR_LMS_SIZE=0x20000 BT_RAMRUN=0 CAPSENSOR_ENABLE=0 CAPSENSOR_AT_SENS=0 CAPSENSOR_SPP_SERVER=0 APP_ANC_ASSIST_THREAD=1 AUDIO_ANC_TT_HW=1 \
SENSORHUB_START_WHEN_MAIN_MCU_ON=0 AUDIO_DEBUG=0 "

build_sensor_hub_cmd="make T=sensor_hub SENS_TRC_TO_MCU=1 CHIP=best1502p VOICE_ASSIST_FF_FIR_LMS=1 MCU_I2C_SLAVE=1 LARGE_SENS_RAM=1 SENS_USE_SENS_MAIN=1 SPEECH_ARMCC_LIB=0 APP_MCPP_CLI=SENS \
APP_MCPP_SRV=bes APP_MCPP_BTH_SENS=1 AUDIO_ANC_FIR_HW=1 FIR_LMS_AEC_ENABLED=0 CP_IN_SAME_EE=1 SENS_FIR_LMS_SIZE=0x20000 VOICE_ASSIST_FF_FIR_LMS_CP_ACCEL=1 VOICE_ASSIST_FF_FIR_LMS_MULTI_THREAD=0 FREEMAN_ENABLED_STERO=1 \
 $LIB_DIR_CFG -j64"

build_ota_copy_cmd="make T=prod_test/ota_copy -j CHIP=best1502p OTA_BIN_COMPRESSED=1 OTA_CODE_OFFSET=0x12000 SINGLE_WIRE_DOWNLOAD=0 USB_CDC_DOWNLOAD=1 DEBUG=0 \
PROGRAMMER_WATCHDOG=1 ALLOW_WARNING=1 $LIB_DIR_CFG "

build_cust_cmd="make T=best1502p -j IGNORE_POWER_ON_KEY_DURING_BOOT_UP=1 IS_AUTOPOWEROFF_ENABLED=0 APP_TRACE_RX_ENABLE=0 APP_RX_API_ENABLE=0 \
TRACE_BUF_SIZE=40*1024 POWER_ON_ENTER_FREEMAN_PAIRING_ENABLED=1 FREEMAN_ENABLED_STERO=1 BLE=1 GATT_OVER_BR_EDR=1 SWIFT_ENABLE=1 AUDIO_ADC_DC_AUTO_CALIB=1 ADC_DC_CALIB_USE_FIXED_DC=1 AUDIO_OUTPUT_SET_LARGE_ANA_DC=1 ALLOW_WARNING=1 \
LEA_ENABLE=1 AOB_CODEC_CP=1 BES_OTA=0 OTA_CODE_OFFSET=0x12000 OTA_BIN_COMPRESSED=1 TOTA_v2=1 A2DP_AAC_ON=1 A2DP_LDAC_ON=1 A2DP_LHDCV5_ON=0 AAC_IN_ROM=1 CVSD_IN_ROM=1 LC3_IN_ROM_V2=1 \
SPEECH_TX_DC_FILTER=1 SPEECH_TX_AEC2FLOAT=0 SPEECH_TX_1MIC_NS=0 SPEECH_TX_2MIC_NS8=1 SPEECH_TX_EQ=1 SPEECH_RX_NS2FLOAT=1 SPEECH_RX_EQ=1 A2DP_VIRTUAL_SURROUND_STEREO=0 HEAD_TRACK_ENABLE=0 AUDIO_ADJ_EQ_REV=1 AUDIO_LIMITER=1 \
ANC_ENABLE=1 ANC_ASSIST_ENABLED=1 ANC_FF_CHECK=1 A2DP_KARAOKE=1 USE_TRACE_ID=0 BTHOST_DEBUG=1 USB_CDC_DOWNLOAD=1 \
A2DP_CP_ACCEL=1 SCO_CP_ACCEL=1 CHIP_HAS_CP=1 RAMCP_SIZE=0x8000 RAMCPX_SIZE=0x10000 FAST_XRAM_SECTION_SIZE=0x8000 UNIFY_HEAP_ENABLED=0 \
BT_USB_AUDIO_DUAL_MODE=1 USB_AUDIO_SEND_CHAN=1 USB_AUDIO_DYN_CFG=1 USB_AUDIO_96K=1 USB_AUDIO_48K=1 USB_AUDIO_44_1K=0 USB_AUDIO_16K=0 USB_AUDIO_16BIT=0 USB_AUDIO_32BIT=0 USB_AUDIO_24BIT=1 AUDIO_PLAYBACK_24BIT=1 USB_AUDIO_SPEECH=1 BTUSB_DUAL_MODE_SUPPORT=1 \
USB_COMM=1 AUDIO_LINEIN=1 $FIR_ANC_CFG $LIB_DIR_CFG -j64"

if [[ "$COMMAND" == "clean" ]];
then
    $build_ota_copy_cmd clean ||{ echo "$LINENO command failed"; exit 1; }
    $build_sensor_hub_cmd clean ||{ echo "$LINENO command failed"; exit 1; }
    $build_cust_cmd clean ||{ echo "$LINENO command failed"; exit 1; }
elif [[ "$COMMAND" == "gen_lib" ]];
then
    $build_ota_copy_cmd GEN_LIB=1 ||{ echo "$LINENO command failed"; exit 1; }
    $build_sensor_hub_cmd GEN_LIB=1 ||{ echo "$LINENO command failed"; exit 1; }
    $build_cust_cmd GEN_LIB=1 ||{ echo "$LINENO command failed"; exit 1; }
elif [[ "$COMMAND" == 'lst' ]];
then
    $build_sensor_hub_cmd lst all ||{ echo "$LINENO command failed"; exit 1; }
    $build_cust_cmd lst all ||{ echo "$LINENO command failed"; exit 1; }
else
    $build_ota_copy_cmd||{ echo "$LINENO command failed"; exit 1; }
    $build_sensor_hub_cmd ||{ echo "$LINENO command failed"; exit 1; }
    $build_cust_cmd ||{ echo "$LINENO command failed"; exit 1; }
fi
echo $build_ota_copy_cmd
echo $build_sensor_hub_cmd
echo $build_cust_cmd