# rm -rf out/

TARGET_LIST="best1306p"
CHIPID="best1306p"
COMMAND=$1
set -e

BUILD_CUSTOMER_CFG="IGNORE_POWER_ON_KEY_DURING_BOOT_UP=1 IS_AUTOPOWEROFF_ENABLED=1 APP_TRACE_RX_ENABLE=1 APP_RX_API_ENABLE=1 AUDIO_DEBUG_CMD=0 \
                    TRACE_BUF_SIZE=40*1024 USE_TRACE_ID=0 BLE=1 GATT_OVER_BR_EDR=0 BES_OTA=1 OTA_BIN_COMPRESSED=1 POWER_ON_ENTER_TWS_PAIRING_ENABLED=1 \
                    FREE_TWS_PAIRING_ENABLED=0 SPEECH_TX_DC_FILTER=1 DUAL_MIC_RECORDING=1 RECORDING_USE_OPUS=1 SPEECH_TX_AEC2FLOAT=0 \
                    SPEECH_TX_2MIC_PREAF=1 SPEECH_TX_2MIC_NS11=1 SPEECH_TX_EQ=0 CAPSENSOR_WEAR_USE_ONE_PAD=1 MUTE_FRAME_DETECT=1 BT_CLOSE_A2DP=1\
                    A2DP_AAC_ON=1 A2DP_LDAC_ON=0 A2DP_LHDC_ON=0 A2DP_LHDC_V3=0 A2DP_LHDCV5_ON=0 AAC_IN_ROM=1 CVSD_IN_ROM=1 \
                    CAPSENSOR_ENABLE=1 ANC_ASSIST_ENABLED=0 BES_LIB_DIR=lib/bes/best1306p/PRO_0017 AFH_ASSESS=1 \
                    RAMCP_SIZE=0x4000 RAMCPX_SIZE=0x10000 FAST_XRAM_SECTION_SIZE=0x6000 UNIFY_HEAP_ENABLED=0 \
                    A2DP_VIRTUAL_SURROUND=1"

if [[ "$COMMAND" == "clean" ]];
then
    make T=$TARGET_LIST clean ||{ echo "$LINENO command failed"; exit 1; }
elif [[ "$COMMAND" == "gen_lib" ]];
then
    make T=$TARGET_LIST $BUILD_CUSTOMER_CFG -j64 GEN_LIB=1 ||{ echo "$LINENO command failed"; exit 1; }
    make T=prod_test/ota_copy CHIP=$CHIPID DEBUG=1 -j64 BES_LIB_DIR=lib/bes/best1306p/PRO_0017 GEN_LIB=1 ||{ echo "$LINENO command failed"; exit 1; }
elif [[ $1 == 'lst' ]];
then
    make T=$TARGET_LIST $BUILD_CUSTOMER_CFG -j64 lst all ||{ echo "$LINENO command failed"; exit 1; }
else
    make T=prod_test/ota_copy CHIP=$CHIPID BES_OTA=1 OTA_BIN_COMPRESSED=1 DEBUG=1 -j64
    make T=$TARGET_LIST $BUILD_CUSTOMER_CFG  -j64 ||{ echo "$LINENO command failed"; exit 1; }
fi

echo $BUILD_CUSTOMER_CFG