obj-y := 

obj-y += apple_cert/
obj-y += features/
obj-y += protocol/
obj-y += transport/

subdir-ccflags-y += \
    -Ibthost/service/iap2/apple_cert \
    -Ibthost/service/iap2/features \
    -Ibthost/service/iap2/protocol \
    -Ibthost/service/iap2/transport \
    -Iplatform/hal/ \
    $(BLUETOOTH_ADAPTER_INCLUDES)