#!/usr/bin/env bash

[ -z "$1" ] &&{
    echo "Mode is Null !!!"
    echo "tws or stereo"
    exit
}

MODE=$1
CLEAN=$2

if [[ $MODE == "tws" ]];
then
    FREEMAN_ENABLED_STERO=0
    FIR_LMS_AEC_ENABLED=1
    SPEECH_ARMCC_LIB=1
elif [[ $MODE == "stereo" ]];
then
    FREEMAN_ENABLED_STERO=1
    FIR_LMS_AEC_ENABLED=0
    SPEECH_ARMCC_LIB=0
fi

if [[ $MODE == "tws" ]];
then
echo "Build Speech Lib"
make T=noapp_test RTOS=0 COMPILE_ONLY=1 GEN_LIB=1 DSP_LIB=1 SPEECH_LIB=1 multimedia/speech/src TOOLCHAIN=armclang ALLOW_WARNING=1 -j CHIP=best1502p AUDIO_ANC_FIR_HW=1 SPEECH_ARMCC_LIB=1 FREEMAN_ENABLED_STERO=$FREEMAN_ENABLED_STERO $CLEAN
fi

echo "Build Sensorhub"
make T=sensor_hub -j8 SENS_TRC_TO_MCU=1 CHIP=best1502p VOICE_ASSIST_FF_FIR_LMS=1 MCU_I2C_SLAVE=1 LARGE_SENS_RAM=1 SENS_USE_SENS_MAIN=1 SPEECH_ARMCC_LIB=$SPEECH_ARMCC_LIB APP_MCPP_CLI=SENS APP_MCPP_SRV=bes APP_MCPP_BTH_SENS=1 AUDIO_ANC_FIR_HW=1 FIR_LMS_AEC_ENABLED=$FIR_LMS_AEC_ENABLED CP_IN_SAME_EE=1 SENS_FIR_LMS_SIZE=0x20000 VOICE_ASSIST_FF_FIR_LMS_CP_ACCEL=1 VOICE_ASSIST_FF_FIR_LMS_MULTI_THREAD=0 FREEMAN_ENABLED_STERO=$FREEMAN_ENABLED_STERO $CLEAN

echo "Build App"
make T=best1502p -j ANC_ENABLE=1 APP_TRACE_RX_ENABLE=1 APP_RX_API_ENABLE=1 APP_MCPP_CLI=BTH APP_MCPP_BTH_SENS=1 POWER_ON_ENTER_FREEMAN_PAIRING_ENABLED=1 AUDIO_DEBUG_CMD=1 SENSOR_HUB=1 APP_RPC_ENABLE=1 SENS_TRC_TO_MCU=1 VOICE_ASSIST_FF_FIR_LMS=1 ANC_ASSIST_ENABLED=1 VOICE_ASSIST_FF_FIR_LMS_BTH_SENS=1 LARGE_SENS_RAM=1 SENS_FIR_LMS_SIZE=0x20000 BT_RAMRUN=0 CAPSENSOR_ENABLE=0 CAPSENSOR_AT_SENS=0 CAPSENSOR_SPP_SERVER=0 APP_ANC_ASSIST_THREAD=1 AUDIO_ANC_TT_HW=1 SENSORHUB_START_WHEN_MAIN_MCU_ON=0 AUDIO_DEBUG=0 FREEMAN_ENABLED_STERO=$FREEMAN_ENABLED_STERO $CLEAN
